Repository PyCQA/isort, pull requests merged in 2022-12, with the labels that each got.

#2022 Fix integration tests
  tests/integration/test_projects_using_isort.py
Labels: test_bug

#2029 Update isort on formatting plugin to 5.11.0
  example_isort_formatting_plugin/poetry.lock
  example_isort_formatting_plugin/pyproject.toml
Labels: integration

#2032 Only call `colorama.init` if `colorama` is available
  isort/format.py
Labels: bug

#2026 Add release workflow
  .github/workflows/release.yml
Labels: ci

#2040 Fix settings for py3.11
  .github/workflows/lint.yml
  isort/settings.py
  isort/stdlibs/__init__.py
  isort/stdlibs/py3.py
  isort/stdlibs/py35.py
  tests/unit/test_importable.py
Labels: bug

#2041 General CI improvements
  .github/labels.yml
  .github/release-drafter.yml
  .github/workflows/constraints.txt
  .github/workflows/integration.yml
  .github/workflows/labeler.yml
  .github/workflows/lint.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  poetry.lock
Labels: ci

#2042 Fix packaging pypoetry
  .flake8
  poetry.lock
  pyproject.toml
  tests/integration/test_projects_using_isort.py
Labels: bug

#2047 Fix detect new version condition
  .github/workflows/release.yml
Labels: skip-changelog

#2048 Bump version 5.11.3
  CHANGELOG.md
  pyproject.toml
Labels: skip-changelog

#2049 Revert version
  pyproject.toml
Labels: skip-changelog

#2050 Revert set-output changes
  .github/workflows/release.yml
Labels: skip-changelog

#2051 Bump version 5.11.3
  docs/configuration/pre-commit.md
  isort/_version.py
  pyproject.toml
Labels: skip-changelog

#2058 Bump Poetry 1.3.1
  .github/workflows/constraints.txt
  .github/workflows/integration.yml
  .github/workflows/lint.yml
  .github/workflows/poetry-constraints.txt
  .github/workflows/release.yml
  .github/workflows/test.yml
Labels: dependencies

#2059 Bump version 5.11.4
  CHANGELOG.md
  docs/configuration/pre-commit.md
  isort/_version.py
  pyproject.toml
Labels: skip-changelog
