Repository PyCQA/isort, pull requests merged in 2025-01, with the labels that each got.

#2334 Updates round 3
  isort/api.py
  isort/deprecated/finders.py
  isort/literal.py
  isort/settings.py
  isort/sorting.py
  poetry.lock
  pyproject.toml
  tests/integration/test_hypothesmith.py
  tests/integration/test_setting_combinations.py
  tests/unit/test_isort.py
  tests/unit/test_setuptools_command.py
Labels: enhancement

#2345 Fix misc unsafe dependencies
  example_isort_formatting_plugin/poetry.lock
  example_isort_formatting_plugin/pyproject.toml
  poetry.lock
Labels: dependencies

#2302 Allow `--diff` to be used with `--jobs`
  isort/main.py
Labels: bug

#2346 UV replacement of Poetry
  .github/workflows/constraints.txt
  .github/workflows/hatch-constraints.txt
  .github/workflows/integration.yml
  .github/workflows/lint.yml
  .github/workflows/poetry-constraints.txt
  .github/workflows/release-dev.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  Dockerfile
  docs/contributing/1.-contributing-guide.md
  docs/quick_start/1.-install.md
  example_isort_formatting_plugin/poetry.lock
  example_isort_formatting_plugin/pyproject.toml
  example_isort_formatting_plugin/uv.lock
  example_isort_sorting_plugin/poetry.lock
  example_isort_sorting_plugin/pyproject.toml
  example_isort_sorting_plugin/uv.lock
  example_shared_isort_profile/poetry.lock
  example_shared_isort_profile/pyproject.toml
  example_shared_isort_profile/uv.lock
  isort/setuptools_commands.py
  poetry.lock
  pyproject.toml
  scripts/clean.sh
  scripts/lint.sh
  scripts/test.sh
  scripts/test_integration.sh
  tests/unit/test_isort.py
  tests/unit/test_settings.py
  uv.lock
Labels: ci

#2349 UV replacement of Poetry
  .github/workflows/constraints.txt
  .github/workflows/integration.yml
  .github/workflows/lint.yml
  .github/workflows/poetry-constraints.txt
  .github/workflows/release-dev.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  Dockerfile
  docs/contributing/1.-contributing-guide.md
  docs/quick_start/1.-install.md
  example_isort_formatting_plugin/poetry.lock
  example_isort_formatting_plugin/pyproject.toml
  example_isort_formatting_plugin/uv.lock
  example_isort_sorting_plugin/poetry.lock
  example_isort_sorting_plugin/pyproject.toml
  example_isort_sorting_plugin/uv.lock
  example_shared_isort_profile/poetry.lock
  example_shared_isort_profile/pyproject.toml
  example_shared_isort_profile/uv.lock
  isort/setuptools_commands.py
  poetry.lock
  pyproject.toml
  scripts/clean.sh
  scripts/lint.sh
  scripts/test.sh
  scripts/test_integration.sh
  tests/unit/test_isort.py
  tests/unit/test_settings.py
  uv.lock
Labels: ci

#2354 Link GH as changelog
  pyproject.toml
Labels: bug
